---
- name: Remove unwanted packages
  ansible.builtin.dnf:
    name:
      - iw*firmware
      - cockpit*
    state: absent

- name: Install essentail packages
  ansible.builtin.dnf:
    name:
      - vim
      - mtr
      - git
    state: latest
