---
# vars file for harden_os
knot_sysctl_parameters:
  - { name: 'net.core.wmem_max', value: 1048576 }
  - { name: 'net.core.wmem_default', value: 1048576 }
  - { name: 'net.core.rmem_max', value: 1048576 }
  - { name: 'net.core.rmem_default', value: 1048576 }
  - { name: 'net.core.busy_read', value: 0 }
  - { name: 'net.core.busy_poll', value: 0 }
  - { name: 'net.core.netdev_max_backlog', value: 40000 }
  - { name: 'net.core.optmem_max', value: 20480 }

bind_sysctl_parameters:
  - { name: 'net.core.rmem_default', value: 1048576 }
  - { name: 'net.core.wmem_default', value: 1048576 }

kernel_sysctl_settings:
  - { name: 'net.ipv4.conf.default.accept_source_route', value: 0 }
  - { name: 'kernel.sysrq', value: 0 }
  - { name: 'kernel.core_uses_pid', value: 1 }
  - { name: 'net.ipv4.tcp_syncookies', value: 1 }
  - { name: 'kernel.msgmnb', value: 65536 }
  - { name: 'kernel.msgmax', value: 65536 }
  - { name: 'kernel.shmmax', value: 68719476736 }
  - { name: 'kernel.shmall', value: 4294967296 }
  - { name: 'net.ipv4.ip_forward', value: 1 }
  - { name: 'net.ipv6.conf.all.forwarding', value: 1 }
  - { name: 'net.ipv4.conf.all.rp_filter', value: 2 }
  - { name: 'net.ipv4.conf.default.rp_filter', value: 2 }
  - { name: 'net.netfilter.nf_conntrack_max', value: 900000 }
  - { name: 'net.ipv6.conf.{{ interface_name }}.accept_dad', value: 0 }
  - { name: 'net.ipv4.conf.{{ interface_name }}.arp_ignore', value: 1 }
  - { name: 'net.ipv4.conf.{{ interface_name }}.arp_announce', value: 1 }
  - { name: 'net.ipv4.conf.{{ interface_name }}.arp_ignore', value: 1 }
  - { name: 'net.ipv4.conf.{{ interface_name }}.arp_announce', value: 1 }
  - { name: 'net.ipv4.neigh.{{ interface_name }}.base_reachable_time', value: 14400 }
  - { name: 'net.ipv4.neigh.{{ interface_name }}.base_reachable_time', value: 14400 }
  - { name: 'net.ipv6.conf.{{ interface_name }}.autoconf', value: 0 }
  - { name: 'net.ipv6.conf.{{ interface_name }}.autoconf', value: 0 }
  - { name: 'net.ipv4.tcp_max_syn_backlog', value: 4096 }
  - { name: 'net.core.somaxconn', value: 32768 }
  - { name: 'net.core.netdev_max_backlog', value: 16384 }
  - { name: 'net.core.dev_weight', value: 64 }
  - { name: 'net.ipv4.ip_local_port_range', value: '16384 65535' }

